config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'users#my_tasks'

  resources :groups do
    resources :tasks, except: [:index]
    put '/update_tasks/:id', to: 'tasks#complete_instance', as: :task_complete
    put '/claim_task/:id', to: 'tasks#claim', as: :task_claim
    put '/claim_all/:id', to: 'tasks#claim_all', as: :task_claim_all
  end

  resources :users, only: [:show]

  get '/join_group' => 'user_group_assignments#new'
  post '/join_group' => 'user_group_assignments#create'
  delete '/leave_group' => 'user_group_assignments#destroy'
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :group
  belongs_to :user, optional: true
  has_many :task_instances, dependent: :destroy
  validates :title, presence: true

  before_save :next_task_instance

  def recurring?
    recurrence_type != ''
  end

  def next_task_instance
    return unless current_instance ? current_instance.complete : true

    new_task_instance = next_instance
    if (repeat_until ? (next_task_instance.due_date > repeat_until) : false) || (quantity ? (completed_instances.count >= quantity) : false)
      nil
    else
      new_task_instance.user = user
      task_instances << new_task_instance
    end
  end

  def current_instance
    task_instances.last
  end

  def completed_instances
    task_instances.filter(&:complete).sort_by(&:due_date).reverse!
  end

  private

  def next_instance
    next_due_date = (current_instance ? current_instance.due_date : due_date) + date_offset
    TaskInstance.new(due_date: next_due_date, user: user)
  end

  # rubocop:disable Metrics/CyclomaticComplexity
  def date_offset
    case recurrence_type
    when '' || nil
      0
    when 'Daily'
      (separation || 0)
    when 'Weekly'
      7 * separation
    when 'Monthly'
      separation.months
    when 'Yearly'
      separation.years
    end
  end
  # rubocop:enable Metrics/CyclomaticComplexity
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy complete_instance claim claim_all]
  before_action :set_group, only: %i[new edit show update create complete_instance claim claim_all]

  def claim_all
    @task.user = current_user
    @task.save

    redirect_to group_task_path(@group, @task)
  end

  def claim
    unless @task.current_instance.complete
      task_instance = @task.current_instance
      task_instance.user = current_user
      task_instance.save
    end

    redirect_to group_task_path(@group, @task)
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new(group_id: group_id)
  end

  # GET /tasks/1/edit
  def edit; end

  def complete_instance
    task_instance = @task.current_instance
    task_instance.user = current_user
    task_instance.complete = true

    unless task_instance.save
      flash[:alert] = 'Error completing task'
      go_to_task
    end

    @task.next_task_instance if @task.recurring?

    redirect_to group_task_path(@group, @task)
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.group_id = group_id

    respond_to do |format|
      if @task.save
        format.html { redirect_to group_path(@group), notice: 'Task was successfully created.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to group_task_path(id: @task.id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to group_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params.permit(:id)[:id])
  end

  def set_group
    @group = Group.find(group_id)
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :recurrence_type, :separation, :user_id,
                                 :visibility_delay, :quantity, :repeat_until)
  end

  def group_id
    params.permit(:group_id)[:group_id]
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<script type="text/javascript">
  $(function () {
    $("#task_recurrence_type").change(function () {
        const category = $(this).val().toLowerCase();
        if (category != "") {
          $(".toggle").show();
          $('.separation_unit').text(category.substr(0, category.length-2).replace('i', 'y')+'s');
          $('.due_date').text("First due on");
        } else {
          $(".toggle").hide();
          $('.due_date').text("Due on");
        }
    });
  });

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

<%= form_with(model: task, url: group_tasks_path) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label 'Due on', :class => 'due_date' %>
    <%= form.date_field :due_date, :value => (Time.now+1.days).strftime('%Y-%m-%d') %>
  </div>

  <div class="field">
    <%= form.label :recurrence_type %>
    <%= form.select :recurrence_type, options_for_select([["None", ""], "Daily", "Weekly", "Monthly", "Yearly"]), :class => 'genForm_dropBox' %>
  </div>
  
  <div class="field toggle" style="display:none">
    <%= form.label "Repeat every" %>
    <%= form.number_field :separation, :value => 1 %>
    <%= form.label 'days', :class => 'separation_unit' %>
  </div>

  <details class="toggle py-2" style="display:none">
    <summary>Optional recurrence settings</summary>
    
    <div class="field px-2"
      data-toggle="tooltip" 
      data-placement="right" 
      title="Tasks will reoccur automatically until this date."
      style="width:max-content">
        <div class="field toggle pl-2">
          <%= form.label "Repeat until" %>
          <%= form.date_field :repeat_until %>
        </div>
    </div>

    <div class="field px-2"
        data-toggle="tooltip" 
        data-placement="right" 
        title="Tasks will reoccur automatically until this # of instances have occurred."
        style="width:max-content">
        <div class="field pl-2">
          <%= form.label "Repeat for" %>
          <%= form.number_field :quantity %>
          <%= form.label(nil, 'occurrences') %>
        </div>
    </div>
  </details>

  <details class="py-2">
    <summary>Advanced settings</summary>
    
    <div class="field px-2"
      data-toggle="tooltip" 
      data-placement="right" 
      title="All task instances will be auto-assigned to this user. Individual instances can be customized."
      style="width:max-content">
        <%= form.label 'Default assignee' %>
      <%= form.collection_select :user_id, @group.users.order(:last_name), :id, :full_name, include_blank: true %>
    </div>

    <div class="field px-2"
        data-toggle="tooltip" 
        data-placement="right" 
        title="For far-away tasks where you only want a reminder a few days in advance - for example, an annual event you only need a few days' notice for"
        style="width:max-content">
        <%= form.label 'Hide until' %>
      <%= form.number_field :visibility_delay, :default => nil %>
      days
    </div>
  </details>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/_list_instances.erb
<div class="table-responsive text-center table-striped">
  <table class="table">
    <thead>
      <tr>
        <th>Due date</th>
        <th>Completed by</th>
        <th>Completed on</th>
      </tr>
    </thead>

    <tbody>
      <% instances.each do |instance| %>
        <tr>
          <td><%= instance.due_date %></td>
          <td><%= instance.user.full_name %></td>
          <td><%= instance.updated_at.to_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_list_tasks.erb
<div class="table-responsive text-center table-striped">
  <table class="table">
    <thead>
      <tr>
        <% if show_group %>
          <th>Group</th>
        <% end %>
        <th>Title</th>
        <th>Due date</th>
        <th>Recurrence</th>
        <th>Assignee</th>
        <th>Done?</th>
      </tr>
    </thead>

    <tbody>
      <% tasks.each do |instance| %>
        <tr>
        <% if show_group %>
          <th><%= instance.group.title %></th>
        <% end %>
          <td><%= link_to "#{instance.task.title}", group_task_path(instance.group, instance.task) %></td>
          <td><%= instance.due_date %></td>
          <td><%= instance.task.recurrence_type %></td>
          <td><%= instance.user&.full_name %></td>
          <td>
            <%= button_to 'Mark done', group_task_complete_path(instance.task.group, instance.task), class:"btn btn-success btn-sm", method: :put %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/_past_instances.erb
<div class="table text-center table-striped">
  <table class="table">
    <thead>
      <tr>
        <th>Due date</th>
        <th>Completed by</th>
        <th>Completed on</th>
      </tr>
    </thead>

    <tbody>
      <% instances.each do |instance| %>
        <tr>
          <td><%= instance.due_date %></td>
          <td><%= instance.user.full_name %></td>
          <td><%= instance.updated_at.to_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<hr/>

<%= button_to 'Delete task', group_task_path(@group, @task), method: :delete, 
      data: { confirm: 'Are you sure? If this is a recurring task, all future recurrences will also be deleted.' }, 
      class:"btn btn-warning" %>

<div>
  <%= link_to 'Show', group_task_path(@group, @task) %> |
  <%= link_to 'Back', group_path(@group) %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', group_path(@group) %>

app/views/tasks/show.html.erb
<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title">
      <%= @task.title %>
    </h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <%= @task.description %>
    </h6>
    <% if !@task.current_instance&.complete %>
    
      <% if @task.current_instance.notes %>
        <p class="card-text">
          <%= @task.current_instance.notes %>
        </p>
      <% end %>

      <p class="card-text mb-2">
        <% if @task.current_instance.user == current_user %>
          Assigned to me
        <% elsif @task.current_instance.user %>
          Current assignee: <%= @task.current_instance.user&.full_name %>
        <% end %>
      </p>

      <p class="card-text mb-2">
        Due on: <%= @task.current_instance.due_date %>
      </p>
      
      <% if @task.current_instance.user == current_user %>
        <%= button_to 'Mark done', group_task_complete_path(@task.group, @task), class:"btn btn-success", method: :put %>
      <% else %>
        <%= button_to 'Assign to me', group_task_claim_path, class:"btn btn-primary", method: :put %>
      <% end %>

    <% end %>
    <% if @task.recurring? %>
      <footer class="card-footer text-muted mt-3">
        <h6 class="card-subtitle mb-2 text-muted">
          Recurs <%= @task.recurrence_type %>
        </h6>

        <p class="card-text">
          <% if @task.user == current_user %>
            Assigned to me by default
          <% else %>
            <% if @task.user %>
              Default assignee: <%= @task.current_instance.user&.full_name %>
            <% end %>
            <%= button_to 'Assign all to me', group_task_claim_all_path, class:"btn btn-secondary", method: :put %>
          <% end %>
        </p>

      </footer>
    <% end %>
  </div>
</div>

<% if @task.completed_instances.any? %>
  <h3>Past occurrences:</h3>
  <%= render 'past_instances', instances: @task.completed_instances %>
<% end %>

<%= link_to 'Edit', edit_group_task_path(@group, @task) %> |
<%= link_to 'Back', group_path(@group) %>