config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  root to: 'users#my_tasks'

  resources :groups do
    resources :tasks, except: [:index]
    put '/update_tasks/:id', to: 'tasks#complete_instance', as: :task_complete
    put '/claim_task/:id', to: 'tasks#claim', as: :task_claim
    put '/claim_all/:id', to: 'tasks#claim_all', as: :task_claim_all
  end

  resources :users, only: [:show]

  get '/join_group' => 'user_group_assignments#new'
  post '/join_group' => 'user_group_assignments#create'
  delete '/leave_group' => 'user_group_assignments#destroy'
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :user_group_assignments, dependent: :delete_all
  has_many :users, through: :user_group_assignments
  has_many :tasks, dependent: :delete_all
  has_many :task_instances, through: :tasks

  def current_tasks
    task_instances.filter { |task| !task.complete & task.visible? }.sort_by(&:due_date)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :validate_access, only: %i[edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    respond_to do |format|
      ActiveRecord::Base.transaction do
        @group = Group.create!(group_params)
        UserGroupAssignment.create!(group: @group, user: current_user, admin: true)

        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      rescue ActiveRecord::RecordInvalid
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:title, :description)
  end

  def validate_access
    return if current_user.admin?(@group)

    flash[:alert] = 'Access permissions error'
    redirect_to @group
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/views/groups/_current_tasks.erb
<div class="table-responsive text-center">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Notes</th>
        <th>Due date</th>
        <th>Assignee</th>
      </tr>
    </thead>

    <tbody>
      <% group.current_tasks.each do |instance| %>
        <tr>
          <td><%= instance.task.title %></td>
          <td><%= instance.task.description %></td>
          <td><%= instance.notes %></td>
          <td><%= instance.due_date %></td>
          <td><%= instance.user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table class="col-md-3">
  <tr class="field">
    <td>
    <%= form.label :title %>
    </td>
    <td>
    <%= form.text_field :title %>
    </td>
  </tr>

  <tr class="field">
    <td>
    <%= form.label :description %>
    </td>
    <td>
    <%= form.text_area :description %>
    </td>
  </tr>

  <tr class="actions">
    <td>
    <%= form.submit 'Submit', :class => 'btn btn-primary' %>
    </td>
  </tr>
</table>
<% end %>

app/views/groups/_members.html.erb
<div class="table-responsive text-center">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% group.user_group_assignments.each do |assignment| %>
        <tr>
          <td><%= assignment.user.full_name %></td>
          <td><%= assignment.user.email %></td>
          <td><%= assignment.user.admin?(group) ? 'Admin' : 'Member'%></td>
          <td>
            <%= button_to 'Remove from group', leave_group_path(id: assignment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h4>Invite a new member to the group:</h4>
<%= form_with model: group, url: join_group_path, method: :post do |form| %>
  <%= form.hidden_field :id %>

  <div class="field">
    <%= form.text_field :email, placeholder: "User's email" %>
  </div>

  <div class="actions">
    <%= form.submit 'Send invite' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Manage membership</h1>
<%= render 'members', group: @group %>
<hr>

<h1>Edit group info</h1>
<%= render 'form', group: @group %>

<hr>

<%= button_to 'Delete group', @group, method: :delete, 
    data: { confirm: 'Are you sure? This will also delete all related tasks & role assignments' },
    class:"btn btn-danger" %>

<br/>
<br/>

<div>
  <%= link_to 'Show', @group %> |
  <%= link_to 'Back', groups_path %>
</div>

app/views/groups/index.html.erb
<h1>Groups</h1>

<% @groups.each do |group| %>
  <div class="card text-center mb-4">
    <div class="card-body">
      <h5 class="card-title">
        <%= group.title %>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <%= group.description %>
      </h6>

      <div class="btn-group">
        <% if current_user.admin?(group) %>
          <%= button_to 'Admin', edit_group_path(group), class:"btn btn-warning me-2", method: :get %>
        <% end %>
        <%= button_to 'Show', group, class:"btn btn-success", method: :get %>
      </div>
    </div>
  </div>
<% end %>

<%= link_to 'Create a new group', new_group_path %>
<br>
<%= link_to 'Join another group', join_group_path %>

app/views/groups/show.html.erb
<div class="card text-center">
    <div class="card-body">
      <h5 class="card-title">
        <%= @group.title %>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <%= @group.description %>
      </h6>
      <% if current_user.admin?(@group) %>
        <%= button_to 'Admin', edit_group_path(@group), class:"btn btn-warning", method: :get %>
      <% end %>
  </div>
</div>

<h2>Outstanding tasks:</h2>
<%= render 'tasks/list_tasks', tasks: @group.current_tasks, show_group: false %>

<%= button_to 'New Task', new_group_task_path(group_id: @group.id), class:"btn btn-primary", method: :get %>
<br><br>

<%= link_to 'Go back', groups_path %>